import { Component } from '@angular/core';

@Component({
  selector: 'app-run-history',
  templateUrl: './run-history.component.html',
  styleUrls: ['./run-history.component.scss'],
})
export class RunHistoryComponent {
  tableHeader: any = [
    'name',
    'run_id',
    'input',
    'response',
    'status',
    'start',
    'end',
    'duration',
    'succeeded',
    'failed',
    'actions',
  ];
  tableDataSource: any = [
    {
      name: 'Integration 1',
      run_id: '123123',
      input: 'RCX_Group_file_type_203_23-06-01.txt',
      response: 'RCX_Group_file_type_203_23-06-01.txt',
      status: 'Failed',
      start: 'dd/mm/yy hh:mm:ss',
      end: 'dd/mm/yy hh:mm:ss',
      duration: 150,
      succeeded: '123, 523',
      failed: '2',
      actions: ['copy', 'info'],
    },
    {
      name: 'Integration 1',
      run_id: '945654',
      input: 'RCX_Group_file_type_203_25-09-01.txt',
      response: 'RCX_Group_file_type_203_25-09-01.txt',
      status: 'Succeeded',
      start: 'dd/mm/yy hh:mm:ss',
      end: 'dd/mm/yy hh:mm:ss',
      duration: 100,
      succeeded: '342, 563',
      failed: '0',
      actions: ['copy', 'info'],
    },
    {
      name: 'Integration 24',
      run_id: '546444',
      input: 'RCX_Group_file_type_233_10-04-01.txt.txt',
      response: 'RCX_Group_file_type_22_21-10-11.txt',
      status: 'Failed',
      start: 'dd/mm/yy hh:mm:ss',
      end: 'dd/mm/yy hh:mm:ss',
      duration: 98,
      succeeded: '435, 987',
      failed: '9',
      actions: ['copy', 'info'],
    },
    {
      name: 'Integration 342',
      run_id: '879645',
      input: 'RCX_Group_file_type_290_20-12-02.txt',
      response: 'RCX_Group_file_type_921_25-10-01.txt.txt',
      status: 'Succeeded',
      start: 'dd/mm/yy hh:mm:ss',
      end: 'dd/mm/yy hh:mm:ss',
      duration: 47,
      succeeded: '343, 523',
      failed: '10',
      actions: ['copy', 'info'],
    },
    {
      name: 'Integration 857',
      run_id: '568945',
      input: 'RCX_Group_file_type_233_15-09-01.txt',
      response: 'RCX_Group_file_type_344_08-05-01.txt',
      status: 'Failed',
      start: 'dd/mm/yy hh:mm:ss',
      end: 'dd/mm/yy hh:mm:ss',
      duration: 78,
      succeeded: '856, 454',
      failed: '4',
      actions: ['copy', 'info'],
    },
    {
      name: 'Integration 198',
      run_id: '437649',
      input: 'RCX_Group_file_type_301_23-09-02.txt',
      response: 'RCX_Group_file_type_31_26-12-03.txt',
      status: 'Failed',
      start: 'dd/mm/yy hh:mm:ss',
      end: 'dd/mm/yy hh:mm:ss',
      duration: 55,
      succeeded: '234, 523',
      failed: '8',
      actions: ['copy', 'info'],
    },
    {
      name: 'Integration 4854',
      run_id: '348289',
      input: 'RCX_Group_file_type_435_16-02-03.txt',
      response: 'RCX_Group_file_type_3134_26-12-03.txt',
      status: 'Succeeded',
      start: 'dd/mm/yy hh:mm:ss',
      end: 'dd/mm/yy hh:mm:ss',
      duration: 25,
      succeeded: '453, 998',
      failed: '9',
      actions: ['copy', 'info'],
    },
    {
      name: 'Integration 1',
      run_id: '123123',
      input: 'RCX_Group_file_type_203_23-06-01.txt',
      response: 'RCX_Group_file_type_203_23-06-01.txt',
      status: 'Failed',
      start: 'dd/mm/yy hh:mm:ss',
      end: 'dd/mm/yy hh:mm:ss',
      duration: 34,
      succeeded: '123, 523',
      failed: '2',
      actions: ['copy', 'info'],
    },
    {
      name: 'Integration 1',
      run_id: '945654',
      input: 'RCX_Group_file_type_203_25-09-01.txt',
      response: 'RCX_Group_file_type_123_09-09-01.txt',
      status: 'Succeeded',
      start: 'dd/mm/yy hh:mm:ss',
      end: 'dd/mm/yy hh:mm:ss',
      duration: 12,
      succeeded: '342, 563',
      failed: '0',
      actions: ['copy', 'info'],
    },
    {
      name: 'Integration 24',
      run_id: '546444',
      input: 'RCX_Group_file_type_233_10-04-01.txt.txt',
      response: 'RCX_Group_file_type_22_21-10-11.txt',
      status: 'Failed',
      start: 'dd/mm/yy hh:mm:ss',
      end: 'dd/mm/yy hh:mm:ss',
      duration: 43,
      succeeded: '435, 987',
      failed: '9',
      actions: ['copy', 'info'],
    },
  ];
}
